name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2

      - name: Hugo Obsidian - Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.12
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy Garden
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: prophet1906/garden
          publish_dir: ./public
          publish_branch: main
          cname: prophet1906.github.io
